name: adasba_2024
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  excel: ^4.0.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.1.2
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.4
  random_string: ^2.3.1
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.0
  universal_html: ^2.2.4
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lotties/
